### PR TITLE
#136 User Settings

### PR DESCRIPTION
**Pull request by adrian-schnell**
implement #136

### CODE REVIEW

**Comment by adrian-schnell** [comment]
**BLOCKED FOR MERGE**
until #138  is ready for merge!

**Review by sandrich — APPROVED** [review]

**Comment by adrian-schnell** [comment]
new endpoints:
*https://api.defichain-dobby.com/list/summary_interval:*
```
{
  "summaryInterval": [
    "none",
    "daily",
    "daily_2x",
    "daily_3x",
    "hourly"
  ]
}
```


*https://api.defichain-dobby.com/list/timezones:*
```
{
  "timezones": {
    "Pacific/Midway": "(GMT-11:00) Midway Island",
    "US/Samoa": "(GMT-11:00) Samoa",
    "US/Hawaii": "(GMT-10:00) Hawaii",
    "US/Alaska": "(GMT-09:00) Alaska",
    "US/Pacific": "(GMT-08:00) Pacific Time (US &amp;amp; Canada)",
   [....]
    "Asia/Vladivostok": "(GMT+11:00) Vladivostok",
    "Asia/Magadan": "(GMT+12:00) Magadan",
    "Pacific/Auckland": "(GMT+12:00) Auckland",
    "Pacific/Fiji": "(GMT+12:00) Fiji"
  }
}
```

**Comment by adrian-schnell** [comment]
user object at GET /user has a new structure:

```
{
    "userId": "527e5018-d3e2-4f59-99bb-5dacb96422aa",
    "settings": {
        "language": "de",
        "summaryInterval": "hourly",
        "currentRatioEnabled": true,
        "timezone": "UTC",
        "uiPrivacyEnabled": true,
        "uiDashboardHealthSummaryEnabled": false,
        "uiDashboardCollateralInfoEnabled": false,
        "uiDashboardCollateralWaypointsEnabled": true,
        "uiTheme": "auto"
    },
    "vaults": [...]
}
``

**Comment by adrian-schnell** [comment]
update user settings at endpoint:

*PUT /user/settings/*

```
{
    "uiTheme": "dark",
    "language": "de",
    "summaryInterval": "daily_2x",
    "currentRatioEnabled": true,
    "uiPrivacyEnabled": false,
    "uiDashboardHealthSummaryEnabled": false,
    "uiDashboardCollateralInfoEnabled": true,
    "uiDashboardCollateralWaypointsEnabled": false,
    "timezone": "Europe/Berlin"
}
```

(all attributes are optional!)

**Pull request merged**
